name: 'Barry Example Workflow'
inputs:
  who-to-greet:
    default: 'World'
    type: string
    required: true
outputs:
  time:
    description: "The current time"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
